name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Caching
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant permission for gradlew
        run: chmod +x gradlew

      - name: Clear build directory
        run: rm -rf build/libs/*

      - name: Build
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: build
          timeout-minutes: 25
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Curious Curios
          path: build/libs/*.jar
          
      - name: Publish to Modrinth
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: lWN93xWs
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: false
